arch:
  H_cycles: 3
  H_layers: 0
  L_cycles: 4
  L_layers: 2
  expansion: 4
  forward_dtype: bfloat16
  halt_exploration_prob: 0.1
  halt_max_steps: 16
  hidden_size: 256
  loss:
    loss_type: stablemax_cross_entropy
    name: losses@ACTLossHead
  mlp_t: false
  name: recursive_reasoning.trm@TinyRecursiveReasoningModel_ACTV1
  no_ACT_continue: true
  num_heads: 4
  pos_encodings: rope
  puzzle_emb_len: 0
  puzzle_emb_ndim: 0
beta1: 0.9
beta2: 0.95
checkpoint_every_eval: true
checkpoint_path: checkpoints/Nonogram_10x10-ACT-torch/TinyRecursiveReasoningModel_ACTV1
  super-cat
data_paths:
- dataset/nonogram_10x10
data_paths_test: []
ema: true
ema_rate: 0.999
epochs: 1
eval_interval: 1
eval_save_outputs: []
evaluators: []
freeze_weights: false
global_batch_size: 64
load_checkpoint: null
lr: 0.0001
lr_min_ratio: 0.1
lr_warmup_steps: 100
min_eval_interval: 0
project_name: Nonogram_10x10-ACT-torch
puzzle_emb_lr: 0.001
puzzle_emb_weight_decay: 0.1
run_name: TinyRecursiveReasoningModel_ACTV1 super-cat
seed: 42
weight_decay: 0.1
